import Header from "@/component/header";
import '/src/styles/globals.css'
import Footer from "@/component/footer";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <Header/>
      {children}
      <Footer/>
      </body>
    </html>
  )
}
